version: "3.8"

services:
  # --- 1. SERVICE BACKEND
  api:
    container_name: ojek_backend
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
      - TZ=${TZ}
    depends_on:
      - db
    networks:
      - ojek_net

  db:
    container_name: ojek_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ojek_net

networks:
  ojek_net:
    driver: bridge

volumes:
  pgdata:
